# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cschockaert/docker-npm-maven:1.3.0

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn clean install

      # upload docs
      - run:
          name: Install dependencies
          # unsafe-perm needed because no uid/gid found by npm
          command: |
            npm config set unsafe-perm true
            npm install -g --silent gh-pages@2.1.1
            cd ~/repo/
            git clone git@github.com:disassemble-io/disassemble-io.github.io.git
            cd disassemble-io.github.io
            ls ~/repo/
