# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cschockaert/docker-npm-maven:1.3.0

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn clean install

      # create docs
      - run:
          name: Create documentation
          command: mvn dokka:dokka

      # add public fingerprint
      - add_ssh_keys:
          fingeprints:
            - "97:7f:cc:4b:2d:2c:fd:d3:de:3e:97:a6:91:d1:7b:49"

      # upload docs
      - run:
          name: Uploading docs to gh-pages branch
          # unsafe-perm needed because no uid/gid found by npm
          command: |
            npm config set unsafe-perm true
            git clone git@github.com:disassemble-io/disassemble-io.github.io.git
            cd disassemble-io.github.io
            rm -rf ./docs/javanalysis
            mkdir -p ./docs/javanalysis/
            cp -avr ~/repo/target/site/docs/javanalysis ./docs/javanalysis
            git config user.email "sedlarizona@gmail.com"
            git config user.name "Tyler Sedlar"
            git add .
            git commit -am "Update documentation for Javanalysis"
            git push -u origin gh-pages